### ISSUE TITLE
Legacy version issues

### ISSUE THREAD

**Issue by Speiger** [Darkhax/CurseForgeGradle#19]
o/ Recently found your plugin and it is a godsend tool.
Especially since i still support a lot of mc versions with my mods.

I am right now trying to setup the 1.12.2 setup but I am getting a bit of a problem.
whenever i try to compile it i am getting this errror.

```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Minecraft\projects\active\IC2Classic\IC2C-1.12.2\build.gradle' line: 68

* What went wrong:
A problem occurred evaluating root project 'IC2C-1.12.2'.
> org.gradle.api.model.ObjectFactory.fileCollection()Lorg/gradle/api/file/ConfigurableFileCollection;
```

This is the code that i am running.
```groovy
task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
	group 'publishing'
	description 'Publishes the mod to Curseforge'
		
	def mainFile = upload(242942, jar) // LINE 68 that is causing issues.
    mainFile.releaseType = RELEASE_TYPE
    mainFile.displayName = archivesBaseName.replace(" ", "")+"-"+version
    
    def changelog = new File(projectDir, "/changelogs/"+MOD_VERSION.replace(".", "")+".md");
    mainFile.changelog = changelog.exists() ? changelog.getText('UTF-8') : "";
    mainFile.changelogType = 'markdown'
    mainFile.addGameVersion('1.12.2', 'Server', 'Client')
    mainFile.addJavaVersion('Java 8')
    mainFile.addIncompatibility('industrial-craft')
}
```
My gradle version is 4.4.1 and i tried version 1.1.15 and 1.1.18 of this and get the same error.

I already tried a few things with jar because it could be enough things changed that it simply isn't compatible with pre 1.13.x stuff.
Which would be sad.

**Comment by Darkhax** [comment]
Hello, the code at issue here was introduced in 1.1.15 so it's possible rolling back to 1.1.14 may have better compatibility. I haven't tested that much on older versions unfortunately. Does running with --stacktrace give you any additional info about the error?

**Comment by Speiger** [comment]
@Darkhax the only version it finds is 1.0.7 at least from what i found.

**Comment by Speiger** [comment]
Ok i tested it now with 1.0.7 and that doesn't support "Client", "Server" as game version sadly.
But let me get stacktrace running with 1.1.18 so we can at least see what the problem is.

**Comment by Speiger** [comment]
1.0.14 gets the same problem as 1.1.18
```
> org.gradle.api.model.ObjectFactory.fileCollection()Lorg/gradle/api/file/ConfigurableFileCollection;
```

**Comment by Speiger** [comment]
Looks like gradle 4.4.1 is just to old which doesn't support the features you are using.

**Comment by Speiger** [comment]
ok @Darkhax I found a solution to solve this problem, and it is something you could also maybe write a bit of documentation for if you want to provide help to others.

@eigenraven linked me to this fork of forge gradle that supports newer gradle versions.
https://github.com/anatawa12/ForgeGradle-1.2

Using that you can upgrade to at least gradle version 7.4 which your plugin works with just fine.
migration steps are also rather simple.

But that closes this chapter
