### ISSUE TITLE
Gradle message: Version slug 1-15-snapshot was already present.

### ISSUE THREAD

**Issue by ricksouth** [Darkhax/CurseForgeGradle#4]
I'm getting the following message whenever using publishCurseForge. Not sure if it's something on my end, or if it's fixable, but I thought I'll mention it here. Thanks for creating CurseForgeGradle!

=============

$ gradlew publishCurseForge
Daemon will be stopped at the end of the build

Task :publishCurseForge
**Version slug 1-15-snapshot was already present. Former ID 7519. New ID 7751.**

BUILD SUCCESSFUL in 6s

**Comment by Darkhax** [comment]
Hello, yes this is a bug with CurseForge's API/database. They have two 1-15-snapshot categories for some reason. They will need to fix it on their end.
